language: ruby
rvm:
  - 2.5.8

sudo: false

cache:
  directories:
    - "$HOME/.rvm"
    - "$HOME/.vvm"
before_script:
  - "curl https://raw.githubusercontent.com/kana/vim-version-manager/master/bin/vvm | python - setup; true"
  - "source ~/.vvm/etc/login"
  - "vvm update_itself"
  - "vvm use vimorg--v8.2.0803 --install --with-features=huge"
  - "gem install vim-flavor"
  - "vim-flavor install"

script: "vim-flavor test spec/"
